### ISSUE TITLE
AttributeError: 'module' object has no attribute 'GraphDatabaseService'

### ISSUE THREAD

**Issue by rahmaniqbal** [necoma/NECOMAtter#1]
Traceback (most recent call last):
  File "./index.py", line 31, in <module>
    world = NECOMAtter("http://localhost:7474")
  File "/root/Tools/NECOMAtter/NECOMAtter.py", line 25, in __init__
    self.gdb = neo4j.GraphDatabaseService(url + "/db/data/")
AttributeError: 'module' object has no attribute 'GraphDatabaseService'

**Comment by rahmaniqbal** [comment]
What are the required versions of these:
gevent
flask
py2neo
requests
dateutil

**Comment by limura** [comment]
In my environment, it seems to have gone up to the point where it starts once with the following library version.


> % pip list
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Package         Version  
> --------------- ---------
> certifi         2019.9.11
> chardet         3.0.4    
> Click           7.0      
> colorama        0.4.1    
> Flask           1.1.1    
> gevent          1.4.0    
> greenlet        0.4.15   
> idna            2.8      
> itsdangerous    1.1.0    
> Jinja2          2.10.1   
> MarkupSafe      1.1.1    
> mod-wsgi        4.6.7    
> neobolt         1.7.13   
> neotime         1.7.4    
> pip             19.2.3   
> pkg-resources   0.0.0    
> prompt-toolkit  2.0.9    
> py2neo          1.6.1    
> Pygments        2.3.1    
> python-dateutil 2.8.0    
> pytz            2019.2   
> requests        2.22.0   
> setuptools      41.2.0   
> six             1.12.0   
> urllib3         1.24.3   
> wcwidth         0.1.7    
> Werkzeug        0.16.0   
> wheel           0.33.6   


Note that NECOMATter is a project that is over 4 years old and is not currently maintained.
Also, as pip says, Python 2 will also end on January 1, 2020, so I can't find much sense to continue using this project.
